import { test, expect, type Page } from '@playwright/test'
import { readFileSync } from 'node:fs'

const password = process.env.POSCOSEGRAN_AUTH_LOCAL_PASSWORD || readFileSync('backend/.env', 'utf8').match(/^POSCOSEGRAN_AUTH_LOCAL_PASSWORD=(.+)$/m)![1].trim()
async function login(page: Page) {
  await page.goto('/')
  await page.getByLabel('Usuario local').fill('productor')
  await page.getByLabel('Contraseña', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Inicio', exact: true })).toBeVisible()
}

test('acceso → alta → borrador → cuarentena → evento → reevaluación → fuentes', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', e => errors.push(e.message))
  await login(page)
  await page.getByRole('button', { name: 'Registrar unidad', exact: true }).click()
  const suffix = Date.now().toString()
  await page.getByLabel('Nombre del almacén', { exact: true }).fill('Almacén E2E ' + suffix)
  await page.getByLabel('Ubicación', { exact: true }).fill('Cusco')
  await page.getByRole('button', { name: 'Guardar almacén', exact: true }).click()
  await expect(page.getByLabel('Almacén', { exact: true })).not.toHaveValue('')
  await page.getByLabel('Código del lote', { exact: true }).fill('E2E-' + suffix)
  await page.getByRole('button', { name: 'Guardar lote', exact: true }).click()
  await expect(page.getByLabel('Lote', { exact: true })).not.toHaveValue('')
  await page.getByLabel('Nombre del recipiente', { exact: true }).fill('Costal E2E ' + suffix)
  await page.getByLabel('Modalidad', { exact: true }).selectOption('NO_HERMETICO')
  await page.getByRole('button', { name: 'Crear unidad y capturar' }).click()
  await expect(page.getByRole('heading', { name: 'Evaluar unidad' })).toBeVisible()
  await page.getByLabel('Fase', { exact: true }).selectOption('INGRESO')
  await page.getByRole('button', { name: /P3/ }).click()
  await page.getByLabel('Moho visible', { exact: true }).selectOption('true')
  await page.getByLabel('Método · Moho visible', { exact: true }).fill('Inspección visual')
  await page.getByRole('button', { name: /P5/ }).click()
  await page.getByLabel('Inicio del historial', { exact: true }).fill('2026-01-01T09:30')
  await page.getByRole('button', { name: 'Guardar borrador', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Borrador guardado')
  await page.evaluate(() => {
    Object.keys(sessionStorage).filter(k => k.startsWith('captura:')).forEach(k => sessionStorage.removeItem(k))
  })
  await page.reload()
  await expect(page.getByRole('status')).toContainText('Borrador recuperado')
  await page.getByRole('button', { name: /P5/ }).click()
  await expect(page.getByLabel('Inicio del historial', { exact: true })).toHaveValue('2026-01-01T09:30')
  await page.getByRole('button', { name: /P3/ }).click()
  await expect(page.getByLabel('Moho visible', { exact: true })).toHaveValue('true')
  await page.getByRole('button', { name: 'Enviar y evaluar', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Cuarentena', exact: true })).toBeVisible()
  await page.screenshot({ path: 'test-results/resultado-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Ver seguimiento', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Seguimiento', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Registrar admisión', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Guardar actuación' })).toBeDisabled()
  await page.getByRole('button', { name: 'Registrar evento', exact: true }).click()
  await page.getByLabel('Evidencia de la actuación', { exact: true }).fill('Apertura registrada en acta E2E')
  await page.getByRole('button', { name: 'Guardar actuación', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('Registro guardado')
  await page.getByRole('button', { name: 'Reevaluar unidad', exact: true }).click()
  await page.getByRole('button', { name: /P3/ }).click()
  await expect(page.getByLabel('Moho visible', { exact: true })).toHaveValue('DESCONOCIDO')
  await page.getByLabel('Moho visible', { exact: true }).selectOption('false')
  await page.getByLabel('Método · Moho visible', { exact: true }).fill('Nueva inspección visual')
  await page.getByRole('button', { name: 'Enviar y evaluar' }).click()
  await expect(page.getByRole('heading', { name: 'Cuarentena', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Base de Conocimiento' }).click()
  await expect(page.getByRole('heading', { name: 'Base de conocimiento', exact: true })).toBeVisible()
  await page.getByLabel('Buscar regla o término').fill('R19')
  await expect(page.locator('summary').filter({ hasText: 'R19' })).toBeVisible()
  expect(errors).toEqual([])
})

test('sesión y navegación responsive a 360, 768 y 1440 px', async ({ page }) => {
  await login(page)
  for (const width of [360, 768, 1440]) {
    await page.setViewportSize({ width, height: 900 })
    await page.reload()
    await expect(page.getByRole('heading', { name: 'Inicio', exact: true })).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy()
    await page.screenshot({ path: `test-results/inicio-${width}.png`, fullPage: true })
  }
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Iniciar sesión', exact: true })).toBeVisible()
})
