/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil */
        get: operations["perfil_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inicio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Inicio
         * @description Resumen de la unidad de trabajo. Consultar nunca crea ni cierra nada.
         */
        get: operations["inicio_api_v1_inicio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/almacenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Almacenes */
        get: operations["listar_almacenes_api_v1_almacenes_get"];
        put?: never;
        /** Crear Almacen */
        post: operations["crear_almacen_api_v1_almacenes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/almacenes/{id_almacen}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Almacen */
        get: operations["obtener_almacen_api_v1_almacenes__id_almacen__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar Almacen */
        patch: operations["actualizar_almacen_api_v1_almacenes__id_almacen__patch"];
        trace?: never;
    };
    "/api/v1/lotes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Lotes */
        get: operations["listar_lotes_api_v1_lotes_get"];
        put?: never;
        /** Crear Lote */
        post: operations["crear_lote_api_v1_lotes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lotes/{id_lote}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Lote */
        get: operations["obtener_lote_api_v1_lotes__id_lote__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar Lote */
        patch: operations["actualizar_lote_api_v1_lotes__id_lote__patch"];
        trace?: never;
    };
    "/api/v1/unidades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Unidades */
        get: operations["listar_unidades_api_v1_unidades_get"];
        put?: never;
        /** Crear Unidad */
        post: operations["crear_unidad_api_v1_unidades_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Unidad */
        get: operations["obtener_unidad_api_v1_unidades__id_unidad__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar Unidad */
        patch: operations["actualizar_unidad_api_v1_unidades__id_unidad__patch"];
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/borrador": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Borrador */
        get: operations["obtener_borrador_api_v1_unidades__id_unidad__borrador_get"];
        /**
         * Guardar Borrador
         * @description Un borrador no autoriza nada ni invalida el resultado vigente.
         *
         *     Comunicar un hallazgo adverso real exige enviarlo como evaluación o control.
         */
        put: operations["guardar_borrador_api_v1_unidades__id_unidad__borrador_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/evaluaciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluar
         * @description Emite una evaluación. SIN_CONCLUSION_AUTOMATICA es una respuesta exitosa.
         */
        post: operations["evaluar_api_v1_unidades__id_unidad__evaluaciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/evaluaciones/{id_evaluacion}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Evaluacion */
        get: operations["obtener_evaluacion_api_v1_evaluaciones__id_evaluacion__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/historial": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial */
        get: operations["historial_api_v1_unidades__id_unidad__historial_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/vigencia": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar Vigencia */
        get: operations["consultar_vigencia_api_v1_unidades__id_unidad__vigencia_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/controles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Controles */
        get: operations["listar_controles_api_v1_unidades__id_unidad__controles_get"];
        put?: never;
        /**
         * Registrar Control
         * @description 'completo' lo decide el servidor comparando requisitos y observaciones.
         */
        post: operations["registrar_control_api_v1_unidades__id_unidad__controles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/planes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Planes */
        get: operations["listar_planes_api_v1_unidades__id_unidad__planes_get"];
        put?: never;
        /**
         * Registrar Plan
         * @description Registrar un plan no equivale a cumplirlo: solo deja constancia de su existencia.
         */
        post: operations["registrar_plan_api_v1_unidades__id_unidad__planes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/dictamenes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Dictamenes */
        get: operations["listar_dictamenes_api_v1_unidades__id_unidad__dictamenes_get"];
        put?: never;
        /**
         * Emitir Dictamen
         * @description Exige técnico asignado: ser propietario de la unidad no habilita esta acción.
         */
        post: operations["emitir_dictamen_api_v1_unidades__id_unidad__dictamenes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/incidencias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Incidencias */
        get: operations["listar_incidencias_api_v1_unidades__id_unidad__incidencias_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidencias/{id_incidencia}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener Incidencia */
        get: operations["obtener_incidencia_api_v1_incidencias__id_incidencia__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidencias/{id_incidencia}/revisiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Revisiones */
        get: operations["listar_revisiones_api_v1_incidencias__id_incidencia__revisiones_get"];
        put?: never;
        /**
         * Registrar Revision
         * @description Registrar una revisión no autoriza almacenamiento ni cierra el episodio.
         */
        post: operations["registrar_revision_api_v1_incidencias__id_incidencia__revisiones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/incidencias/{id_incidencia}/resoluciones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Resoluciones */
        get: operations["listar_resoluciones_api_v1_incidencias__id_incidencia__resoluciones_get"];
        put?: never;
        /**
         * Resolver Incidencia
         * @description Cierra el episodio con evidencia y disposición: es el único modo de levantarlo.
         */
        post: operations["resolver_incidencia_api_v1_incidencias__id_incidencia__resoluciones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/admisiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar Admision
         * @description No se admite con una vigencia distinta de VIGENTE: se comprueba antes de actuar.
         */
        post: operations["registrar_admision_api_v1_unidades__id_unidad__admisiones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/unidades/{id_unidad}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar Eventos */
        get: operations["listar_eventos_api_v1_unidades__id_unidad__eventos_get"];
        put?: never;
        /** Registrar Evento */
        post: operations["registrar_evento_api_v1_unidades__id_unidad__eventos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/conocimiento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalogo */
        get: operations["catalogo_api_v1_conocimiento_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud */
        get: operations["salud_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/salud/bd": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Salud Bd */
        get: operations["salud_bd_salud_bd_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Accion */
        Accion: {
            /** Codigo */
            codigo: string;
            /** Descripcion */
            descripcion: string;
            /**
             * Responsable Requerido
             * @enum {string}
             */
            responsable_requerido: "PRODUCTOR" | "TECNICO";
            /** Id Incidencia */
            id_incidencia: string | null;
        };
        /** Admision */
        Admision: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /**
             * Id Evaluacion
             * Format: uuid
             */
            id_evaluacion: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "INGRESO" | "CONTINUIDAD";
            /**
             * Registrado En
             * Format: date-time
             */
            registrado_en: string;
            /**
             * Id Responsable
             * Format: uuid
             */
            id_responsable: string;
        };
        /** AdmisionEntrada */
        AdmisionEntrada: {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /**
             * Id Evaluacion
             * Format: uuid
             */
            id_evaluacion: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "INGRESO" | "CONTINUIDAD";
        };
        /** Almacen */
        Almacen: {
            /** Nombre */
            nombre: string;
            /** Ubicacion */
            ubicacion: string;
            /** Clima Calido */
            clima_calido: boolean | null;
            /** Fundamento Clima */
            fundamento_clima: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Revision */
            revision: number;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** AlmacenEntrada */
        AlmacenEntrada: {
            /** Nombre */
            nombre: string;
            /** Ubicacion */
            ubicacion: string;
            /** Clima Calido */
            clima_calido: boolean | null;
            /** Fundamento Clima */
            fundamento_clima: string | null;
        };
        /** Borrador */
        Borrador: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /** Revision */
            revision: number;
            contenido: components["schemas"]["EvaluacionEntrada-Output"];
            /**
             * Actualizado En
             * Format: date-time
             */
            actualizado_en: string;
        };
        /** CalculosTiempo */
        CalculosTiempo: {
            /** Vida Consumida */
            vida_consumida: number | null;
            /** Vida Minima Documentada */
            vida_minima_documentada: number | null;
            /** Vida Proyectada */
            vida_proyectada: number | null;
            /** Tiempo Referencia Actual */
            tiempo_referencia_actual: number | null;
            celda_tabla: components["schemas"]["CeldaTabla"] | null;
        };
        /** Catalogo */
        Catalogo: {
            /** Version Base */
            version_base: string;
            /** Reglas */
            reglas: components["schemas"]["Regla"][];
            /** Ramas R30 */
            ramas_r30: components["schemas"]["Regla"][];
            /** Fuentes */
            fuentes: components["schemas"]["Fuente"][];
        };
        /** CeldaTabla */
        CeldaTabla: {
            /** Id Tabla */
            id_tabla: string;
            /** Humedad Fila */
            humedad_fila: number;
            /** Temperatura Columna F */
            temperatura_columna_f: number;
            /** Dias Referencia */
            dias_referencia: number;
        };
        /** Control */
        Control: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "INGRESO" | "GRANO" | "EXTERIOR" | "ALMACEN";
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /** Completo */
            completo: boolean;
            /** Campos Pendientes */
            campos_pendientes: string[];
            /**
             * Id Responsable
             * Format: uuid
             */
            id_responsable: string;
            /** Evidencia */
            evidencia: string;
        };
        /** ControlEntrada */
        ControlEntrada: {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "INGRESO" | "GRANO" | "EXTERIOR" | "ALMACEN";
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /** Observaciones */
            observaciones: components["schemas"]["ObservacionEntrada"][];
            /** Evidencia */
            evidencia: string;
        };
        /** ControlProximo */
        ControlProximo: {
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /** Nombre */
            nombre: string;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /**
             * Estado
             * @enum {string}
             */
            estado: "PENDIENTE" | "ATRASADO";
        };
        /** DatoPendiente */
        DatoPendiente: {
            /** Campo */
            campo: string;
            /** Motivo */
            motivo: string;
            /**
             * Paso
             * @enum {integer}
             */
            paso: 1 | 2 | 3 | 4 | 5 | 6;
        };
        /** Dictamen */
        Dictamen: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /** Humedad Min */
            humedad_min: number;
            /** Humedad Max */
            humedad_max: number;
            /** Plazo Maximo Dias */
            plazo_maximo_dias: number;
            /**
             * Emitido En
             * Format: date-time
             */
            emitido_en: string;
            /**
             * Vence En
             * Format: date-time
             */
            vence_en: string;
            /** Condiciones */
            condiciones: string;
            /** Evidencia */
            evidencia: string;
            /**
             * Id Tecnico
             * Format: uuid
             */
            id_tecnico: string;
            /** Vigente */
            vigente: boolean;
        };
        /** DictamenEntrada */
        DictamenEntrada: {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /** Humedad Min */
            humedad_min: number;
            /** Humedad Max */
            humedad_max: number;
            /** Plazo Maximo Dias */
            plazo_maximo_dias: number;
            /**
             * Vence En
             * Format: date-time
             */
            vence_en: string;
            /** Condiciones */
            condiciones: string;
            /** Evidencia */
            evidencia: string;
        };
        /** Estimacion */
        Estimacion: {
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "ESTIMACION_HERMETICA" | "SUSTITUCION_TABLA";
            /** Descripcion */
            descripcion: string;
            /** Campos */
            campos: string[];
            /** Id Tabla */
            id_tabla: string | null;
        };
        /** Evaluacion */
        Evaluacion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /**
             * Id Lote
             * Format: uuid
             */
            id_lote: string;
            /**
             * Id Recipiente
             * Format: uuid
             */
            id_recipiente: string;
            /**
             * Id Almacen
             * Format: uuid
             */
            id_almacen: string;
            /**
             * Fecha Evaluacion
             * Format: date-time
             */
            fecha_evaluacion: string;
            /** Fase */
            fase: ("INGRESO" | "SEGUIMIENTO") | null;
            /**
             * Decision Final
             * @enum {string}
             */
            decision_final: "CUARENTENA" | "BLOQUEAR_INGRESO" | "RETIRAR_LOTE" | "CORREGIR_Y_REEVALUAR" | "SIN_CONCLUSION_AUTOMATICA" | "AUTORIZAR_CON_MONITOREO" | "AUTORIZAR_ALMACENAMIENTO";
            /**
             * Rama R30
             * @enum {string}
             */
            rama_r30: "R30.1" | "R30.2" | "R30.3" | "R30.4" | "R30.5" | "R30.6" | "R30.7" | "R30.8" | "R30.9";
            /** Motivos */
            motivos: components["schemas"]["Motivo"][];
            /** Acciones Requeridas */
            acciones_requeridas: components["schemas"]["Accion"][];
            /** Datos Pendientes */
            datos_pendientes: components["schemas"]["DatoPendiente"][];
            /** Estimaciones Y Sustituciones */
            estimaciones_y_sustituciones: components["schemas"]["Estimacion"][];
            /** Reglas Activadas */
            reglas_activadas: string[];
            /** Observaciones Aplicadas */
            observaciones_aplicadas: components["schemas"]["ObservacionValidada"][];
            calculos_tiempo: components["schemas"]["CalculosTiempo"];
            /** Fecha Proximo Control */
            fecha_proximo_control: string | null;
            /** Fecha Vencimiento Autorizacion */
            fecha_vencimiento_autorizacion: string | null;
            /** Version Base */
            version_base: string;
            /** Version Parametros */
            version_parametros: string;
            /** Version Motor */
            version_motor: string;
        };
        /** EvaluacionEntrada */
        "EvaluacionEntrada-Input": {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /** Fase */
            fase: ("INGRESO" | "SEGUIMIENTO") | null;
            /** Observaciones */
            observaciones: components["schemas"]["ObservacionEntrada"][];
            historial: components["schemas"]["HistorialEntrada"];
            /** Dias Previstos Restantes */
            dias_previstos_restantes: number | null;
            /** Fecha Salida Prevista */
            fecha_salida_prevista: string | null;
        };
        /** EvaluacionEntrada */
        "EvaluacionEntrada-Output": {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /** Fase */
            fase: ("INGRESO" | "SEGUIMIENTO") | null;
            /** Observaciones */
            observaciones: components["schemas"]["ObservacionEntrada"][];
            historial: components["schemas"]["HistorialEntrada"];
            /** Dias Previstos Restantes */
            dias_previstos_restantes: number | null;
            /** Fecha Salida Prevista */
            fecha_salida_prevista: string | null;
        };
        /** Evento */
        Evento: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "LIMPIEZA_GENERAL" | "APERTURA" | "RESELLADO" | "SECADO" | "ENFRIAMIENTO" | "EXPOSICION_AGUA" | "CARGA_DESCARGA";
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /** Evidencia */
            evidencia: string;
            /**
             * Id Responsable
             * Format: uuid
             */
            id_responsable: string;
        };
        /** EventoEntrada */
        EventoEntrada: {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "LIMPIEZA_GENERAL" | "APERTURA" | "RESELLADO" | "SECADO" | "ENFRIAMIENTO" | "EXPOSICION_AGUA" | "CARGA_DESCARGA";
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
            /** Evidencia */
            evidencia: string;
        };
        /** EvidenciaMotivo */
        EvidenciaMotivo: {
            /** Campo */
            campo: string;
            /** Valor Observado */
            valor_observado: number | boolean | string | null;
            /** Unidad */
            unidad: ("PCT_BH" | "PCT_HR" | "PCT_MASA" | "CELSIUS" | "METROS" | "DIAS" | "FRACCION" | "BOOLEANO" | "TEXTO") | null;
            /** Fecha Observacion */
            fecha_observacion: string | null;
            /** Operador */
            operador: ("GT" | "GTE" | "LT" | "LTE" | "EQ" | "NEQ" | "PRESENCIA" | "VIGENCIA") | null;
            /** Umbral */
            umbral: number | boolean | string | null;
        };
        /** Fuente */
        Fuente: {
            /** Id */
            id: string;
            /** Referencia Markdown */
            referencia_markdown: string;
        };
        /** FuenteRef */
        FuenteRef: {
            /** Id Fuente */
            id_fuente: string;
            /** Localizador */
            localizador: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistorialEntrada */
        HistorialEntrada: {
            /** Fecha Inicio Historial */
            fecha_inicio_historial: string | null;
            /** Vida Previa Documentada */
            vida_previa_documentada: number | null;
            /** Evidencia Vida Previa */
            evidencia_vida_previa: string | null;
            /** Intervalos Historial */
            intervalos_historial: components["schemas"]["IntervaloEntrada"][];
        };
        /** Incidencia */
        Incidencia: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /** Revision */
            revision: number;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "CUARENTENA" | "REVISION_PLAGAS" | "REVISION_TERMICA" | "CORRECCION";
            /**
             * Estado
             * @enum {string}
             */
            estado: "ABIERTA" | "CERRADA";
            /** Causas */
            causas: string[];
            /**
             * Creada En
             * Format: date-time
             */
            creada_en: string;
            /** Cerrada En */
            cerrada_en: string | null;
        };
        /** Inicio */
        Inicio: {
            /** Unidades Total */
            unidades_total: number;
            /** Cuarentenas Abiertas */
            cuarentenas_abiertas: number;
            /** Correcciones Pendientes */
            correcciones_pendientes: number;
            /** Controles Proximos */
            controles_proximos: components["schemas"]["ControlProximo"][];
        };
        /** IntervaloEntrada */
        IntervaloEntrada: {
            /**
             * Inicio
             * Format: date-time
             */
            inicio: string;
            /**
             * Fin
             * Format: date-time
             */
            fin: string;
            /** Humedad Grano */
            humedad_grano: number | null;
            /** Temperatura Grano */
            temperatura_grano: number | null;
            /** Metodo */
            metodo: string | null;
            /** Evidencia */
            evidencia: string | null;
        };
        /** Lote */
        Lote: {
            /** Codigo */
            codigo: string;
            /**
             * Variedad
             * @constant
             */
            variedad: "MAIZ_CHULPI";
            /**
             * Uso Final
             * @constant
             */
            uso_final: "ALIMENTACION";
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Propietario
             * Format: uuid
             */
            id_propietario: string;
            /** Revision */
            revision: number;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** LoteEntrada */
        LoteEntrada: {
            /** Codigo */
            codigo: string;
            /**
             * Variedad
             * @constant
             */
            variedad: "MAIZ_CHULPI";
            /**
             * Uso Final
             * @constant
             */
            uso_final: "ALIMENTACION";
        };
        /** Motivo */
        Motivo: {
            /** Id */
            id: string;
            /** Regla */
            regla: string;
            /** Mensaje */
            mensaje: string;
            /** Evidencias */
            evidencias: components["schemas"]["EvidenciaMotivo"][];
            /** Fuentes */
            fuentes: components["schemas"]["FuenteRef"][];
            /**
             * Fundamento
             * @enum {string}
             */
            fundamento: "PUBLICADO" | "TRANSFERIDO" | "POLITICA_PROTOTIPO" | "MIXTO";
        };
        /**
         * ObservacionEntrada
         * @description Una omisión significa desconocido: no implica falso, cero ni no aplicable.
         */
        ObservacionEntrada: {
            /** Campo */
            campo: string;
            /**
             * Captura
             * @enum {string}
             */
            captura: "APORTADO" | "DESCONOCIDO" | "NO_APLICA";
            /** Valor */
            valor: number | boolean | string | null;
            /**
             * Unidad
             * @enum {string}
             */
            unidad: "PCT_BH" | "PCT_HR" | "PCT_MASA" | "CELSIUS" | "METROS" | "DIAS" | "FRACCION" | "BOOLEANO" | "TEXTO";
            /** Valor Original */
            valor_original: string | null;
            /** Fecha Observacion */
            fecha_observacion: string | null;
            /** Metodo */
            metodo: string | null;
            /** Evidencia */
            evidencia: string | null;
            /** Motivo No Aplica */
            motivo_no_aplica: string | null;
        };
        /** ObservacionValidada */
        ObservacionValidada: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            entrada: components["schemas"]["ObservacionEntrada"];
            /**
             * Aplicabilidad
             * @enum {string}
             */
            aplicabilidad: "APLICA" | "NO_APLICA";
            /** Estado Dato */
            estado_dato: ("VALIDO" | "DESCONOCIDO" | "INVALIDO" | "VENCIDO") | null;
            /**
             * Id Responsable
             * Format: uuid
             */
            id_responsable: string;
            /**
             * Procedencia
             * @enum {string}
             */
            procedencia: "ACTUAL" | "HISTORICA" | "ESTIMADA";
            /** Incidencias Validacion */
            incidencias_validacion: string[];
        };
        /** Pagina[Almacen] */
        Pagina_Almacen_: {
            /** Items */
            items: components["schemas"]["Almacen"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Control] */
        Pagina_Control_: {
            /** Items */
            items: components["schemas"]["Control"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Dictamen] */
        Pagina_Dictamen_: {
            /** Items */
            items: components["schemas"]["Dictamen"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Evento] */
        Pagina_Evento_: {
            /** Items */
            items: components["schemas"]["Evento"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Incidencia] */
        Pagina_Incidencia_: {
            /** Items */
            items: components["schemas"]["Incidencia"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Lote] */
        Pagina_Lote_: {
            /** Items */
            items: components["schemas"]["Lote"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Plan] */
        Pagina_Plan_: {
            /** Items */
            items: components["schemas"]["Plan"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Resolucion] */
        Pagina_Resolucion_: {
            /** Items */
            items: components["schemas"]["Resolucion"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[ResultadoEvaluacion] */
        Pagina_ResultadoEvaluacion_: {
            /** Items */
            items: components["schemas"]["ResultadoEvaluacion"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Revision] */
        Pagina_Revision_: {
            /** Items */
            items: components["schemas"]["Revision"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Pagina[Unidad] */
        Pagina_Unidad_: {
            /** Items */
            items: components["schemas"]["Unidad"][];
            /** Siguiente Cursor */
            siguiente_cursor: string | null;
        };
        /** Perfil */
        Perfil: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Nombre */
            nombre: string;
            /** Roles */
            roles: ("PRODUCTOR" | "TECNICO" | "ADMINISTRADOR")[];
        };
        /** Plan */
        Plan: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /**
             * Fecha Proximo Control
             * Format: date-time
             */
            fecha_proximo_control: string;
            /** Intervalo Dias */
            intervalo_dias: number;
            /**
             * Fecha Salida Prevista
             * Format: date-time
             */
            fecha_salida_prevista: string;
            /** Actividades */
            actividades: string;
            /** Vigente */
            vigente: boolean;
            /**
             * Id Responsable
             * Format: uuid
             */
            id_responsable: string;
        };
        /** PlanEntrada */
        PlanEntrada: {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /**
             * Fecha Proximo Control
             * Format: date-time
             */
            fecha_proximo_control: string;
            /** Intervalo Dias */
            intervalo_dias: number;
            /**
             * Fecha Salida Prevista
             * Format: date-time
             */
            fecha_salida_prevista: string;
            /** Actividades */
            actividades: string;
        };
        /** Regla */
        Regla: {
            /** Id */
            id: string;
            /** Antecedente */
            antecedente: string;
            /** Consecuente */
            consecuente: string;
            /** Accion */
            accion: string;
            /** Fundamento Markdown */
            fundamento_markdown: string;
        };
        /** Resolucion */
        Resolucion: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Incidencia
             * Format: uuid
             */
            id_incidencia: string;
            /** Evidencia */
            evidencia: string;
            /** Disposicion */
            disposicion: string;
            /**
             * Id Tecnico
             * Format: uuid
             */
            id_tecnico: string;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
        };
        /** ResolucionEntrada */
        ResolucionEntrada: {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /** Revision Incidencia */
            revision_incidencia: number;
            /** Evidencia */
            evidencia: string;
            /** Disposicion */
            disposicion: string;
        };
        /** ResultadoEvaluacion */
        ResultadoEvaluacion: {
            evaluacion: components["schemas"]["Evaluacion"];
            vigencia: components["schemas"]["Vigencia"];
        };
        /** Revision */
        Revision: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Incidencia
             * Format: uuid
             */
            id_incidencia: string;
            /**
             * Resultado
             * @enum {string}
             */
            resultado: "PENDIENTE" | "CONFIRMADA" | "DESCARTADA";
            /** Evidencia */
            evidencia: string;
            /**
             * Id Tecnico
             * Format: uuid
             */
            id_tecnico: string;
            /**
             * Fecha
             * Format: date-time
             */
            fecha: string;
        };
        /** RevisionEntrada */
        RevisionEntrada: {
            /** Revision Unidad */
            revision_unidad: number;
            /** Revision Almacen */
            revision_almacen: number;
            /** Revision Incidencia */
            revision_incidencia: number;
            /**
             * Resultado
             * @enum {string}
             */
            resultado: "PENDIENTE" | "CONFIRMADA" | "DESCARTADA";
            /** Evidencia */
            evidencia: string;
        };
        /** Unidad */
        Unidad: {
            /**
             * Id Lote
             * Format: uuid
             */
            id_lote: string;
            /**
             * Id Almacen
             * Format: uuid
             */
            id_almacen: string;
            /** Nombre Recipiente */
            nombre_recipiente: string;
            /** Tipo Almacenamiento */
            tipo_almacenamiento: ("HERMETICO" | "NO_HERMETICO") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Id Recipiente
             * Format: uuid
             */
            id_recipiente: string;
            /** Revision */
            revision: number;
            /** Revision Almacen */
            revision_almacen: number;
            /** Id Evaluacion Actual */
            id_evaluacion_actual: string | null;
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
        };
        /** UnidadEntrada */
        UnidadEntrada: {
            /**
             * Id Lote
             * Format: uuid
             */
            id_lote: string;
            /**
             * Id Almacen
             * Format: uuid
             */
            id_almacen: string;
            /** Nombre Recipiente */
            nombre_recipiente: string;
            /** Tipo Almacenamiento */
            tipo_almacenamiento: ("HERMETICO" | "NO_HERMETICO") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vigencia */
        Vigencia: {
            /**
             * Id Unidad
             * Format: uuid
             */
            id_unidad: string;
            /** Id Evaluacion */
            id_evaluacion: string | null;
            /**
             * Estado
             * @enum {string}
             */
            estado: "VIGENTE" | "VENCIDA" | "INVALIDADA" | "NO_AUTORIZADO" | "SIN_EVALUACION";
            /**
             * Consultada En
             * Format: date-time
             */
            consultada_en: string;
            /** Fecha Proximo Control */
            fecha_proximo_control: string | null;
            /** Fecha Vencimiento Autorizacion */
            fecha_vencimiento_autorizacion: string | null;
            /** Causas */
            causas: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    perfil_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Perfil"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    inicio_api_v1_inicio_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Inicio"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_almacenes_api_v1_almacenes_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Almacen_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_almacen_api_v1_almacenes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlmacenEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Almacen"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_almacen_api_v1_almacenes__id_almacen__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id_almacen: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Almacen"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_almacen_api_v1_almacenes__id_almacen__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_almacen: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlmacenEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Almacen"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_lotes_api_v1_lotes_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
                q?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Lote_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_lote_api_v1_lotes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_lote_api_v1_lotes__id_lote__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id_lote: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_lote_api_v1_lotes__id_lote__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_lote: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoteEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Lote"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_unidades_api_v1_unidades_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
                id_lote?: string | null;
                id_almacen?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Unidad_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_unidad_api_v1_unidades_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnidadEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unidad"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_unidad_api_v1_unidades__id_unidad__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unidad"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actualizar_unidad_api_v1_unidades__id_unidad__patch: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnidadEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Unidad"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_borrador_api_v1_unidades__id_unidad__borrador_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Borrador"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guardar_borrador_api_v1_unidades__id_unidad__borrador_put: {
        parameters: {
            query?: never;
            header?: {
                "If-Match"?: string | null;
                "If-None-Match"?: string | null;
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluacionEntrada-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Borrador"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluar_api_v1_unidades__id_unidad__evaluaciones_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluacionEntrada-Input"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoEvaluacion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_evaluacion_api_v1_evaluaciones__id_evaluacion__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id_evaluacion: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultadoEvaluacion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historial_api_v1_unidades__id_unidad__historial_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_ResultadoEvaluacion_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    consultar_vigencia_api_v1_unidades__id_unidad__vigencia_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vigencia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_controles_api_v1_unidades__id_unidad__controles_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Control_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_control_api_v1_unidades__id_unidad__controles_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ControlEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Control"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_planes_api_v1_unidades__id_unidad__planes_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Plan_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_plan_api_v1_unidades__id_unidad__planes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_dictamenes_api_v1_unidades__id_unidad__dictamenes_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Dictamen_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    emitir_dictamen_api_v1_unidades__id_unidad__dictamenes_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DictamenEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Dictamen"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_incidencias_api_v1_unidades__id_unidad__incidencias_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
                estado?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Incidencia_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_incidencia_api_v1_incidencias__id_incidencia__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id_incidencia: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Incidencia"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_revisiones_api_v1_incidencias__id_incidencia__revisiones_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_incidencia: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Revision_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_revision_api_v1_incidencias__id_incidencia__revisiones_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_incidencia: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_resoluciones_api_v1_incidencias__id_incidencia__resoluciones_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_incidencia: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Resolucion_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolver_incidencia_api_v1_incidencias__id_incidencia__resoluciones_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_incidencia: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolucionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Resolucion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_admision_api_v1_unidades__id_unidad__admisiones_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdmisionEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Admision"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_eventos_api_v1_unidades__id_unidad__eventos_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limite?: number | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagina_Evento_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    registrar_evento_api_v1_unidades__id_unidad__eventos_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
                authorization?: string | null;
            };
            path: {
                id_unidad: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventoEntrada"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evento"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalogo_api_v1_conocimiento_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalogo"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    salud_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    salud_bd_salud_bd_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
